version: '3.8'
services:
  llm_server:
    build:
      context: ./services/llm-core 
    container_name: llm_server
    ports:
      - "8001:8001"        
    env_file:
      - ./services/llm-core/.env.example  
    volumes:
      - ./services/llm-core:/app    
    command: uvicorn llm_server:app --host 0.0.0.0 --port 8001

  api_gateway:
    build:
      context: ./services/api-gateway 
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - llm_server
    volumes:
      - ./services/api-gateway:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
